services:
  app:
    container_name: audio-handler-app
    build: .
    ports:
      - "8080:8080"
    networks:
      - local_network
    depends_on:
      mysql:
        condition: service_healthy
      localstack:
        condition: service_started

  # LocalStack Service (for S3)
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-1}
      - SERVICES=s3
    volumes:
      - "./aws:/etc/localstack/init/ready.d"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - local_network

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306" # Expose MySQL port
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d # Mount for initializing database
    networks:
      - local_network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

# Define volumes for persistence
volumes:
  mysql_data:
    driver: local
  localstack_data:
    driver: local

# Define network
networks:
  local_network:
    driver: bridge
